### ISSUE TITLE
Have some problems with new SBF files

### ISSUE THREAD

**Issue by liu1106-steady** [Algafix/OSNMA#2]
I use the new SBF file with GALRaw INAV to run this code, but it shows that "FileNotFoundError: [Errno 2] No such file or directory". I make sure that I set the correct file path.

![2c021a6f2f58954f8ebabd4e9c4b1ff](https://user-images.githubusercontent.com/82949819/178140851-546bb414-5e6d-4bb5-b073-cd5e9b886836.png)
![9f65dc8d20d743c25a67de271153a36](https://user-images.githubusercontent.com/82949819/178140858-c6d81788-bdc8-41e9-a4d1-bcaab50f51ca.png)
![880b1fd57955164cee9f2963634ad8b](https://user-images.githubusercontent.com/82949819/178140861-2c8e75b1-eb6c-4570-a1e1-7f4d03a12fb6.png)

**Comment by Algafix** [comment]
Working on a general fix for the windows paths.

In the meanwhile, can you try if one of these formats work?

```
'scenario_path': r'D:/path/to/file.sbf'
'scenario_path': 'D:\\path\\to\\file.sbf'
```

**Comment by liu1106-steady** [comment]
> 正在处理窗口路径的常规修复。
> 
> 同时，您能尝试这些格式之一是否有效吗？
> 
> ```
> 'scenario_path': r'D:/path/to/file.sbf'
> 'scenario_path': 'D:\\path\\to\\file.sbf'
> ```

I tried, but I still failed.

**Comment by Algafix** [comment]
Can you test it with the changes on the `windows_path_fix` branch?

https://github.com/Algafix/OSNMA/tree/windows_path_fix

**Comment by liu1106-steady** [comment]
I

> 你能用分支上的更改来测试它吗？`windows_path_fix`
> 
> https://github.com/Algafix/OSNMA/tree/windows_path_fix

Thanks, I will try it later

**Comment by liu1106-steady** [comment]
> I
> 
> > 你能用分支上的更改来测试它吗？`windows_path_fix`
> > https://github.com/Algafix/OSNMA/tree/windows_path_fix
> 
> Thanks, I will try it later

I failed again, lol. It is normal a few days ago, I can run it, but it occurs error today.

**Comment by liu1106-steady** [comment]
> > I
> > > 你能用分支上的更改来测试它吗？`windows_path_fix`
> > > https://github.com/Algafix/OSNMA/tree/windows_path_fix
> > 
> > 
> > Thanks, I will try it later
> 
> I failed again, lol. It is normal a few days ago, I can run it, but it occurs error today.

I have solved the problem that occurred yesterday, it was caused by the file extension. Thanks again for your help.
