### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by albsantosandres** [Algafix/OSNMA#24]
Dear colleague,
I am trying to run your OSNMA code using the following SW:
- Windows 10 Pro
- Python 3.10.0, 3.10.6 and 3.10.7
- Data source: Galmon
I properly download the dependencies in the requirements.txt file ... but I always get the following output (even waiting 30min) with no additional information . However my brother succeeded to get authentication information with a MAC.
Have you got similar problems?

_```
_H:\osnma\OSNMA-master\live_galmon_run>python run.py
Running using GALMON live data.
INFO -
Start status COLD_START

WARNING - Cannot compute Padding length: Missing attribute NB_DP
INFO - Public Key 2 read. Start status WARM_START_
```_

**Comment by Algafix** [comment]
Just another question: are you running from the last release or have you clonned the repo? 

I did some changes to improve the galmon input that I haven't added to any release, so I would recommend you to test it with the cloned repository

**Comment by albsantosandres** [comment]
Hi again,
Thanks a lot for your prompt reply. Find below my answers:
1) The custom_run works properly and I can see the authentication outputs.
2) I have tried a telnet command (equivalent to nc) to the indicated IP and port and it works properly as I can see binary data output.
3) In the previous try, I download the zip. Now I cloned the repo but it still fails. 
4) Requested output after uncommented lines:

Alberto@DESKTOP-M58RF78 MINGW64 ~/osnma/OSNMA/live_galmon_run (master)
$ python run.py
Running using GALMON live data.
INFO - 
Start status COLD_START

WARNING - Cannot compute Padding length: Missing attribute NB_DP
INFO - Public Key 2 read. Start status WARM_START

Traceback (most recent call last):
  File "C:\Users\Alberto\osnma\OSNMA\live_galmon_run\..\osnma\input_formats\input_galmon.py", line 56, in __next__
    sync = self.s.recv(4, socket.MSG_WAITALL)
OSError: [WinError 10045] Se intentó una operación que no es compatible con el tipo de objeto requerido

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alberto\osnma\OSNMA\live_galmon_run\run.py", line 30, in <module>
    live_galmon_config()
  File "C:\Users\Alberto\osnma\OSNMA\live_galmon_run\run.py", line 24, in live_galmon_config
    osnma_r.start()
  File "C:\Users\Alberto\osnma\OSNMA\live_galmon_run\..\osnma\receiver\receiver.py", line 160, in start
    for page in self.nav_data_input:
  File "C:\Users\Alberto\osnma\OSNMA\live_galmon_run\..\osnma\input_formats\input_galmon.py", line 107, in __next__
    print(f"Failed:\n{nmm}")
UnboundLocalError: local variable 'nmm' referenced before assignment

**Comment by albsantosandres** [comment]
For the provided error, It sounds to be a Windows issue when managing the socket. Maybe I will try using Linux.....

**Comment by Algafix** [comment]
Thank you for checking it!

It seems an easy-to-reproduce error, maybe windows doesn't like the `socket.MGS_WAITALL` . I'll configure the windows VM and work on a fix this weekend :)

**Comment by Algafix** [comment]
Hello! I just pushed a fix for the galmon input.

Let me know if it works for you :)
