### ISSUE TITLE
MACK process gets stucked due to invalid mack subfames accumulated when no tesla chain is in force yet

### ISSUE THREAD

**Issue by cicco84** [Algafix/OSNMA#6]
In the module **"receiver_state.py",** the method **process_mack_subframe** accumulates new mack_subfames in the **_self.kroot_waiting_mack_** list if the **_self.tesla_chain_force_** is None.

If one of the accumulated mack subframe causes an exception (e.g.: _MackParsingError_ and/or _TeslaKeyVerificationFailed_), it will be kept in the _self.kroot_waiting_mack_ causing a continuous loop over the same wrong/invalid mack subfame

It is suggested to modify the method according to what follows:

    def process_mack_subframe(self, mack_subframe, gst_subframe, svid, sf_nma_status):

        if self.nma_status == NMAS.DONT_USE:
            logger.warning(f"NMA Status: Don't Use. Subframe tags not processed.")
            self.kroot_waiting_mack = []
            return

        if self.tesla_chain_force is None:
            self.kroot_waiting_mack.append((mack_subframe, gst_subframe, svid, sf_nma_status))
        else:
            try:
                if self.kroot_waiting_mack:
                    for w_mack in self.kroot_waiting_mack:
                        self.tesla_chain_force.parse_mack_message(w_mack[0], w_mack[1], w_mack[2], w_mack[3])
                    self.kroot_waiting_mack = []
                self.tesla_chain_force.parse_mack_message(mack_subframe, gst_subframe, svid, sf_nma_status)
                self.tesla_chain_force.update_tag_lists()

            except MackParsingError as e:
                # Unable to parse the message correctly
                logger.error(f"ERROR: Unable to parse the MACK message correctly.\n{e}")
                if self.start_status == StartStates.HOT_START:
                    self._fallback_to_warm_start()
                **else:
                    logger.warning(f"WARNING: Deleting mack message from waiting list")
                    self.kroot_waiting_mack = self.kroot_waiting_mack[1:]**
            except TeslaKeyVerificationFailed as e:
                # Unable to verify the TESLA key
                logger.error(f"Failed authenticating a TESLA key.\n{e}")
                if self.start_status == StartStates.HOT_START:
                    self._fallback_to_warm_start()
                **else:
                    logger.warning(f"WARNING: Deleting mack message from waiting list")
                    self.kroot_waiting_mack = self.kroot_waiting_mack[1:]**
            else:
                if self.start_status == StartStates.HOT_START:
                    self.start_status = StartStates.STARTED
                    logger.info(f"One TESLA key verified. Start Status: {self.start_status.name}")

**Comment by Algafix** [comment]
Thanks for the report again!

As with the other issue, I'll test and update the code, and mention you.
