### ISSUE TITLE
Combined with GNSS-SDR

### ISSUE THREAD

**Issue by FayeWong98** [Algafix/OSNMA#8]
Hello, your tool currently supports SBF and Galmon input. 

Have you considered combining it with GNSS-SDR tools? This tool can receive and decode Galileo navigation messages.

Looking forward to your reply and wish you a happy life!

**Comment by Algafix** [comment]
Hello!

I have never used that tool, but I can look at it and see how easy would it be to combine them.

Thanks for the info :)

**Comment by FayeWong98** [comment]
Hello, I noticed that OSNMA has updated the public key and other files. 

When I re-import the public key file and combine it with the data actually received by the receiver, the following error appears on the console:
...
raise ValueError(f"IOD from tag {tag.id} and data don't match: Tag {tag.iod_tag[-3:]} - Data {iod[-3:]}.")
ValueError: IOD from tag (5, 0, 7) and data don't match: Tag 0b111 - Data 0b011.

It seems that there is an error in IOD matching. I hope you can continue to improve OSNMAlib. 
Thank you!

**Comment by Algafix** [comment]
Hello Faye!

Indeed OSNMA was updated in August, but it was more than just the public key and merkle root. There are also internal changes to how the data is handled and it is not backwards compatible.

That is why I created a new branch on GitHub with the changes: https://github.com/Algafix/OSNMA/tree/OSNMA_ICD_1.0

Try to use that branch with the new data and let me know if it works :)

PD1: Starting tomorrow, OSNMA plans to transmit the definitive version. Then I will move the branch with the new version to master and move the current master to a branch. I will let you know here.

PD2: I took a look at GNSS-SDR, seems feasible to be implemented, expect it to be added in a week or so.

**Comment by FayeWong98** [comment]
Thank you very much for your work. 

How do you know the latest news about OSNMA? 
It is difficult for me to find the complete plan of OSNMA on the euspa website.

**Comment by Algafix** [comment]
Hello!

I have moved the new OSNMA configuration to main, so no need of using the branch OSNMA_ICD_1.0. However, if you want to use old data, use the [Test Phase ICD branch](https://github.com/Algafix/OSNMA/tree/OSNMA_Test_Phase_ICD)


For the news, you can find the OSNMA definition documents [here](https://www.gsc-europa.eu/electronic-library/programme-reference-documents#OSNMA).

It may also be interesting to keep at eye on the service notices and nagus [here](https://www.gsc-europa.eu/system-service-status/service-notices).

You can also register on the website and choose to get the nagu's and news to your mail under the Subscriptions tab of your profile.
